### PR TITLE
fix: rename sentry dsn var name

### LINKED ISSUE #14: Fix wrong Sentry DSN env var name
should be `REACT_APP_SENTRY_DSN` instead of `SENTRY_DSN`

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes the same of the sentry DSN variable. It is passed as `REACT_APP_SENTRY_DSN` by the graasp-deploy workflows.

closes #14

### CODE REVIEW

File: src/config/sentry.ts [hunk 1]
```diff
@@ -25,8 +26,9 @@ export const generateSentryConfig = (): SentryConfigType => {
   }
 
   return {
-    dsn: (!window.Cypress && process.env.SENTRY_DSN) || '',
+    dsn: (!window.Cypress && process.env.REACT_APP_SENTRY_DSN) || '',
     environment: SENTRY_ENVIRONMENT,
     tracesSampleRate: SENTRY_TRACE_SAMPLE_RATE,
+    release: process.env.REACT_APP_VERSION || 'no version',
```
Comment (mochiruntime) [inline src/config/sentry.ts]: Should we use `undefined` rather than `"no version"` to model the absence of value?

Comment (spaenleh) [reply src/config/sentry.ts]: Yes `undefined` is a good idea, i will update it.

Comment (mochiruntime) [reply src/config/sentry.ts]: @spaenleh I was actually thinking about using the JS `undefined` value, i.e. not as a string (see [stringly-typed](https://wiki.c2.com/?StringlyTyped))

Comment (spaenleh) [reply src/config/sentry.ts]: Mhmm but in this case, we don't need a default value, because `process.env.REACT_APP_VERSION` does not exist then it will be `undefined` by default no ?

Comment (mochiruntime) [reply src/config/sentry.ts]: Yes, but do you want to use a string because you want to set a default value to the html meta tag?

Comment (spaenleh) [reply src/config/sentry.ts]: The version tag in the HTML is auto-replaced by CRA. If `REACT_APP_VERSION` is not set it will just be the empty string. This here is just to configure which release is associated to the sentry events that are sent. Does that make sense ?

**Review by mochiruntime — APPROVED** [review]
